CREATE DATABASE IF NOT EXISTS MULTIMODAL_CUSTOMER_SERVICE;

USE DATABASE MULTIMODAL_CUSTOMER_SERVICE;

CREATE SCHEMA IF NOT EXISTS DATA;

USE SCHEMA MULTIMODAL_CUSTOMER_SERVICE.DATA;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

CREATE OR REPLACE STAGE MULTIMODAL_CUSTOMER_SERVICE.DATA.CUSTOMER_CALLS_EXTERNAL
  URL = 's3://sfquickstarts/extracting-insights-from-multimodal-customer-data/AUDIO_DATA/'
  DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE MULTIMODAL_CUSTOMER_SERVICE.DATA.CUSTOMER_CALLS
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);

COPY FILES
  INTO @CUSTOMER_CALLS
  FROM @CUSTOMER_CALLS_EXTERNAL;

ALTER STAGE MULTIMODAL_CUSTOMER_SERVICE.DATA.CUSTOMER_CALLS REFRESH;

CREATE OR REPLACE TABLE DATA.audio_file_list AS 
SELECT 
    RELATIVE_PATH AS file_name
FROM DIRECTORY(@MULTIMODAL_CUSTOMER_SERVICE.DATA.Customer_Calls);

CREATE OR REPLACE STAGE MULTIMODAL_CUSTOMER_SERVICE.DATA.COMPANY_DOCUMENTS
  URL = 's3://sfquickstarts/extracting-insights-from-multimodal-customer-data/DOCUMENT_DATA/'
  DIRECTORY = (ENABLE = TRUE);

CREATE TABLE IF NOT EXISTS transcription_results (
    -- Primary identifiers
    transcription_id VARCHAR(100) PRIMARY KEY DEFAULT ('trans_' || UUID_STRING()),
    stage_location VARCHAR(500) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    
    timestamp_granularity VARCHAR(20) DEFAULT 'speaker',
    
    audio_duration FLOAT NOT NULL,
    segments VARIANT NOT NULL,
    
    raw_response VARIANT NOT NULL,
    
    translated_text VARCHAR,
    call_category VARCHAR,
    
    sentiment_label VARCHAR(20),

    call_summary VARCHAR,
    
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    transcription_completed_at TIMESTAMP_NTZ
);

CREATE OR REPLACE STAGE MULTIMODAL_CUSTOMER_SERVICE.DATA.TABLE_DATA
  URL = 's3://sfquickstarts/extracting-insights-from-multimodal-customer-data/TABLE_DATA/'
  DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE FILE FORMAT csv_format
  TYPE = 'CSV'
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE TABLE CHAT_LOGS
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@TABLE_DATA/chat_logs.csv',
      FILE_FORMAT => 'csv_format'
    )
  )
);

COPY INTO CHAT_LOGS
FROM @TABLE_DATA/chat_logs.csv
FILE_FORMAT = (FORMAT_NAME = 'csv_format')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE SUPPORT_TICKETS
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@TABLE_DATA/support_tickets.csv',
      FILE_FORMAT => 'csv_format'
    )
  )
);

COPY INTO SUPPORT_TICKETS
FROM @TABLE_DATA/support_tickets.csv
FILE_FORMAT = (FORMAT_NAME = 'csv_format')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;